services:
  postgres_mcdonalds:
    image: postgres:14.5
    environment:
      POSTGRES_PORT: "5432"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "senha"
      PORT : "5432"
      TZ: America/Sao_Paulo
    ports:
      - "5432:5432"
    volumes:
      - postgres_volume:/var/lib/postgres
      - ./sql/mcdonalds_health_db.sql:/docker-entrypoint-initdb.d/A_mcdonalds_health_db.sql
      - ./sql/alter_table_types_every_numerical_type_column.sql:/docker-entrypoint-initdb.d/B_alter_table.sql
volumes:
  postgres_volume:

#relation "public.fast_food_nutrition_menu" does not exist